version: "3.8"
services:
  mockserver:
    image: mockserver/mockserver
    ports:
      - 1080:1080
    environment:
      MOCKSERVER_INITIALIZATION_JSON_PATH: "/config/mockserver.json"
      MOCKSERVER_WATCH_INITIALIZATION_JSON: "true"
    volumes:
      - type: bind
        source: .
        target: /config
